require('dotenv').config({ path: '../.env' });
const { signAccessToken } = require('../backend/src/utils/jwt.utils');
const { verifyAccessToken } = require('./src/utils/jwt.utils');

const mockUser = { userId: "60c72b2f9b1d8e001f3e4b5c", role: "user" };
console.log("Secret:", process.env.JWT_ACCESS_SECRET);

const token = signAccessToken(mockUser);
console.log("Token generated by backend:", token);

try {
    const decoded = verifyAccessToken(token);
    console.log("Decoded successfully by chat-service:", decoded);
} catch (err) {
    console.error("Chat service verification failed:", err.message);
}
