import { Helmet } from 'react-helmet-async'

export default function Privacy() {
    return (
        <div className="static-page">
            <Helmet>
                <title>Privacy Policy | PeerNet</title>
            </Helmet>

            <header className="static-page__header static-page__header--left">
                <h1 className="static-page__title">Privacy Policy</h1>
                <p className="static-page__meta">Last updated: July 30, 2026</p>
            </header>

            <section className="static-page__section">
                <h2>What we collect</h2>
                <p>
                    When you create an account we store your username, email address and password (as a
                    hash, never in plain text). If you sign in with Google we store the email and
                    display name Google returns. Anything you choose to add to your profile — full name,
                    bio, website, avatar — is stored as you entered it.
                </p>
                <p>
                    Posts, comments, stories, likes, follows and direct messages are stored so the app
                    can show them back to you and to the people you shared them with. Server logs
                    record request paths and timestamps for debugging and abuse prevention.
                </p>
            </section>

            <section className="static-page__section">
                <h2>Who can see it</h2>
                <p>
                    Your profile, posts and comments are public — anyone with a link can view them.
                    Saved posts are visible only to you. Direct messages are visible to the people in
                    the conversation.
                </p>
                <p>
                    Direct messages are <strong>not</strong> end-to-end encrypted. They travel over
                    HTTPS and are stored in our database in readable form, which means a site
                    administrator could in principle read them. Do not use PeerNet direct messages for
                    anything you need cryptographic secrecy for.
                </p>
            </section>

            <section className="static-page__section">
                <h2>Third parties</h2>
                <p>
                    Images and videos you upload are stored and served by Cloudinary. Sign-in with
                    Google uses Google Identity Services. Default profile pictures are generated by
                    ui-avatars.com from your username. We do not sell your data or run advertising.
                </p>
            </section>

            <section className="static-page__section">
                <h2>Your choices</h2>
                <p>
                    You can edit or clear your profile fields, and delete your own posts, comments and
                    conversations, at any time from the app. To delete your account and the data
                    attached to it, use the Report Bug link in the footer and ask — requests are handled
                    manually.
                </p>
            </section>
        </div>
    )
}
